# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tracker
  pod "Parse"
  pod "AlamofireImage"

  target 'TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
